### ISSUE TITLE
indoor cam not supported

### ISSUE THREAD

**Issue by frimar75** [OpenWonderLabs/homebridge-switchbot-openapi#255] opened 2021-08-05 14:48 UTC
{"deviceId":"bfb4d6d36c1ab66d74vbte","deviceName":"IndoorCam","enableCloudService":true,"hubDeviceId":"FFFFFFFFFFFF"}

"Device: Indoor Cam with Device Type: undefined, is currently not supported."

I wish it would be supported ;)

Greets

frimar75

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donavanbecker** [comment] 2021-09-02 01:56
Closing duplicate of #268

**Closed by donavanbecker** 2021-09-02 01:56 UTC
Labels: enhancement
